sudo: required
services:
  -dcoker

before_install:
 - docker build -t amitjaindockerhub/docker-react -f Dockerfile.dev .

script:
 - docker run amitjaindockerhub/docker-react npm run test -- --coverage
