sudo: required
services:
  -docker

before_install:
 - docker build -t amitjaindockerhub/docker-react -f Dockerfile.dev .

script:
 - docker run amitjaindockerhub/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-app-deployment"
  env: "DockerAppDeployment-env"
  bucket_name: "elasticbeanstalk-ap-south-1-083625559372"
  bucket_path: "docker-app-deployment"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

